src/Entity/Product.php
<?php
namespace App\Entity;

use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 * @Vich\Uploadable
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Manufacturer;

    /**
     * @ORM\Column(type="text", length=4096)
     */
    private $Brief;

    /**
     * @ORM\Column(type="float")
     */
    private $Price;

    /**
     * @ORM\Column(type="boolean")
     */
    private $TopSale;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\PharmGroup", inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    private $PharmGroup;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\MedicinalForm", inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    private $MedicinalForm;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\TargetAnimals", inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    private $TargetAnimals;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="product_images", fileNameProperty="image")
     * @var File
     */
    private $imageFile;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getManufacturer(): ?string
    {
        return $this->Manufacturer;
    }

    public function setManufacturer(string $Manufacturer): self
    {
        $this->Manufacturer = $Manufacturer;

        return $this;
    }

    public function getBrief(): ?string
    {
        return $this->Brief;
    }

    public function setBrief(string $Brief): self
    {
        $this->Brief = $Brief;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->Price;
    }

    public function setPrice(float $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getTopSale(): ?bool
    {
        return $this->TopSale;
    }

    public function setTopSale(bool $TopSale): self
    {
        $this->TopSale = $TopSale;

        return $this;
    }

    public function getPharmGroup(): ?PharmGroup
    {
        return $this->PharmGroup;
    }

    public function setPharmGroup(?PharmGroup $PharmGroup): self
    {
        $this->PharmGroup = $PharmGroup;

        return $this;
    }

    public function getMedicinalForm(): ?MedicinalForm
    {
        return $this->MedicinalForm;
    }

    public function setMedicinalForm(?MedicinalForm $MedicinalForm): self
    {
        $this->MedicinalForm = $MedicinalForm;

        return $this;
    }

    public function getTargetAnimals(): ?TargetAnimals
    {
        return $this->TargetAnimals;
    }

    public function setTargetAnimals(?TargetAnimals $TargetAnimals): self
    {
        $this->TargetAnimals = $TargetAnimals;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($image) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updatedAt = new \DateTime('now');
        }
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\ViewAllNews;
use App\Service\ViewAllProducts;
use App\Repository\NewsItemRepository;
use App\Repository\ProductRepository;



class MainController extends AbstractController
{
    /**
     * @Route("/", name="main")
     */
    public function index(ProductRepository $productRepository, ViewAllProducts $productService)
    {
        $products = $productService->getAllProducts();
        return $this->render('main/index.html.twig', compact('products'));
    }

    /**
     * @Route("/about", name="about")
     */
    public function about()
    {
        return $this->render('main/about.html.twig');
    }

    /**
     * @Route("/news", name="news")
     */
    public function news(NewsItemRepository $newsRepository, ViewAllNews $myService)
    {
        $news = $myService->getAllNews();
        return $this->render('main/news.html.twig', compact('news'));
    }

    /**
     * @Route("/order", name="order")
     */
    public function order()
    {
        return $this->render('main/order.html.twig');
    } 
    
}

templates/main/about.html.twig
{% extends 'base.html.twig' %}

{% block title %}О компании | Nova{% endblock %}

{% block content %}

<div class="col-sm-12">    			   			
	<h2 class="title text-center">О <strong> компании</strong></h2>    			    				    				
</div>
<p align="justify">ООО «NOVA» - это уникальное фармацевтическое предприятие, работающее в сфере производства оригинальных лекарственных препаратов с 1994 года, которое имеет полный цикл выпуска: разработка, создание и внедрение в производство лекарственных средств. Единицы фармацевтических компаний могут позволить себе такие этапы, как разработка и создание оригинального лекарственного препарата, так как это дорогое и долгосрочное дело.

В настоящее время компания имеет в своем распоряжении современное, технически оснащенное производство, которое состоит из трех основных подразделений: участок мягких лекарственных форм, участок экстракционных препаратов и участок лекарственных сборов. Располагая новыми технологиями и современным подходом к обучению персонала, предприятие ежегодно наращивает темпы производства.

Современный подход к качеству производимой продукции и заготовке качественного лекарственного растительного сырья, произрастающего в экологически чистых районах Украины, делает продукцию востребованной и конкурентоспособной на рынке фитопрепаратов.

Все препараты компании имеют в своем составе исключительно природные (растительного и животного происхождения) компоненты, лечебные свойства которых издавна использовались в традиционной и народной медицине.</p>


{% endblock %}

templates/main/contacts.html.twig
{% extends 'base.html.twig' %}

{% block title %}Контакты | Nova{% endblock %}

{% block content %}

<div id="contact-page" class="container">
    	<div class="bg">
	    	<div class="row">    		
	    		<div class="col-sm-12">    			   			
					<h2 class="title text-center">Наши <strong>Контакты</strong></h2>
					{% include 'flash_messages.html.twig' %}    			    				    				
					<div id="gmap" class="contact-map">
					<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d3050.884793500653!2d36.18864533304313!3d49.98364555085159!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sru!2sua!4v1545241938755" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
					</div>
				</div>			 		
			</div>
			</br>    	
    		<div class="row">  	
	    		<div class="col-sm-8">
	    			<div class="contact-form">
	    				<h2 class="title text-center">Напишите нам</h2>
	    				<div class="status alert alert-success" style="display: none"></div>
						
				    	<form id="main-contact-form" class="contact-form row" name="contact-form" method="post">
						{{ form_start(our_form) }}
				            <div class="form-group col-md-6">
								{{ form_row(our_form.name) }}
				            </div>
				            <div class="form-group col-md-6">
								{{ form_row(our_form.email) }}
				            </div>
				            <div class="form-group col-md-12">
								{{ form_row(our_form.subject) }}
				            </div>
				            <div class="form-group col-md-12">
								{{ form_row(our_form.message) }}
				            </div>
							{{ form_row(our_form._token) }}                        
				            <div class="form-group col-md-12">
				                <input type="submit" name="submit" class="btn btn-primary pull-right" value="Отправить">
				            </div>
							{{ form_end(our_form) }}
				        </form>
						
	    			</div>
	    		</div>
	    		<div class="col-sm-4">
	    			<div class="contact-info">
	    				<h2 class="title text-center">Наш адрес</h2>
	    				<address>
	    					<p>Nova Inc.</p>
							<p>б-р Независимости, 18-а, г. Бровары, Киевская обл.</p>
							<p>Украина, 07400</p>
							<p>Телефон: +38 044 599 32 24</p>
							<p>Факс: +38 044 599-32-27</p>
							<p>Email:  office@brovafarma.com.ua</p>
	    				</address>
	    				<div class="social-networks">
	    					<h2 class="title text-center">Мы в соцсетях</h2>
							<ul>
								<li>
									<a href="#"><i class="fa fa-facebook"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-twitter"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-google-plus"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-youtube"></i></a>
								</li>
							</ul>
	    				</div>
	    			</div>
    			</div>    			
	    	</div>  
    	</div>	
    </div><!--/#contact-page-->

{% endblock %}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Главная | Nova{% endblock %}

{% block content %}
<div class="features_items"><!--products-->
	<h2 class="title text-center">Продукция</h2>

        {% for item in products %}

		<div class="col-sm-4">
			<div class="product-image-wrapper">
				<div class="single-products">
					<div class="productinfo text-center">
						<img src="/images/products/{{ item.image }}" alt="" />
						<h2>{{ item.price|number_format(2, ',', '.') }} грн.</h2>
						<p>{{ item.name }}</p>
						<a href="/view/{{item.id}}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Подробнее</a>
					</div>
                    {% if item.TopSale %}
                    <img src="images/home/sale.png" class="new" alt="" />
                    {% endif %}
				</div>
			</div>
		</div>

        {% endfor %}

</div><!--products-->
<div class="recommended_items"><!--top_sale-->
	<h2 class="title text-center">Топ продаж</h2>
        <div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
			<div class="carousel-inner">
				<div class="item active">
                {% set i = 0 %}
                {% for item in products %}
                    {% if item.TopSale %}	
                        {% set i = i + 1 %}
                            {% if i < 4 %}
                                <div class="col-sm-4">
                                    <div class="product-image-wrapper">
                                        <div class="single-products">
                                            <div class="productinfo text-center">
                                                <img src="/images/products/{{ item.image }}" alt="" />
                                                <h2>{{ item.price|number_format(2, ',', '.') }} грн.</h2>
                                                <p>{{ item.name }}</p>
                                                <a href="/view/{{item.id}}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Подробнее</a>				
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                    {% endif %}
                {% endfor %}
				</div>
                <div class="item">
                {% set i = 0 %}
                {% for item in products %}
                    {% if item.TopSale %}	
                        {% set i = i + 1 %}
                            {% if i > 3 %}
                                <div class="col-sm-4">
                                    <div class="product-image-wrapper">
                                        <div class="single-products">
                                            <div class="productinfo text-center">
                                                <img src="/images/products/{{ item.image }}" alt="" />
                                                <h2>{{ item.price|number_format(2, ',', '.') }} грн.</h2>
                                                <p>{{ item.name }}</p>
                                                <a href="/view/{{item.id}}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Подробнее</a>				
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                    {% endif %}
                {% endfor %}
				</div>
			</div>
							 <a class="left recommended-item-control" href="#recommended-item-carousel" data-slide="prev">
								<i class="fa fa-angle-left"></i>
							  </a>
							  <a class="right recommended-item-control" href="#recommended-item-carousel" data-slide="next">
								<i class="fa fa-angle-right"></i>
							  </a>			
		</div>
</div>
{% endblock %}

templates/main/news.html.twig
{% extends 'base.html.twig' %}

{% block title %}Новости | Nova{% endblock %}

{% block content %}

<div class="col-sm-12">    			   			
	<h2 class="title text-center"><strong> Новости</strong></h2>    			    				    				
</div>
<div class="blog-post-area">
	<div class="single-blog-post">
		{% for newsItem in news|reverse %}
			<h3>{{ newsItem.title }}</h3>
				<div class="post-meta">
					<ul>
						<li><i class="fa fa-calendar"></i> {{ newsItem.createdAt | date("m/d/Y") }}</li>
					</ul>
				</div>
				<p align="justify">{{ newsItem.content | raw}}</p>
		{% endfor %}
	</div>
</div>
	
{% endblock %}

templates/main/order.html.twig
{% extends 'base.html.twig' %}

{% block title %}Login | Nova{% endblock %}

{% block content %}

<div class="col-sm-12">    			   			
	<h2 class="title text-center"><strong>Оформить заказ</strong></h2>    			    				    				
</div>

<section id="cart_items">
		<div class="container">
            <div class="shopper-informations">
				<div class="row">
					<div class="col-sm-5 clearfix">
						<div class="bill-to">
							<p>Ваши данные</p>
							<div class="form-one">
								<form>
									<input type="text" placeholder="Имя *">
									<input type="text" placeholder="Фамилия *">
									<input type="text" placeholder="Телефон *">
									<input type="text" placeholder="E-mail*">
									<input type="text" placeholder="Address 2">
								</form>
							</div>
						</div>
					</div>					
				</div>
			</div>
			<div class="review-payment">
				<h2>ЗАКАЗ</h2>
			</div>

			<div class="table-responsive cart_info">
				<table class="table table-condensed">
					<thead>
						<tr class="cart_menu">
							<td class="image">Продукт</td>
							<td class="description"></td>
							<td class="price">Цена</td>
							<td class="quantity">Количество</td>
							<td class="total">Итого</td>
							<td></td>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td class="cart_product">
								<a href=""><img src="images/cart/one.png" alt=""></a>
							</td>
							<td class="cart_description">
								<h4><a href="">Colorblock Scuba</a></h4>
								<p>Web ID: 1089772</p>
							</td>
							<td class="cart_price">
								<p>$59</p>
							</td>
							<td class="cart_quantity">
								<div class="cart_quantity_button">
									<a class="cart_quantity_up" href=""> + </a>
									<input class="cart_quantity_input" type="text" name="quantity" value="1" autocomplete="off" size="2">
									<a class="cart_quantity_down" href=""> - </a>
								</div>
							</td>
							<td class="cart_total">
								<p class="cart_total_price">$59</p>
							</td>
							<td class="cart_delete">
								<a class="cart_quantity_delete" href=""><i class="fa fa-times"></i></a>
							</td>
						</tr>

						<tr>
							<td class="cart_product">
								<a href=""><img src="images/cart/two.png" alt=""></a>
							</td>
							<td class="cart_description">
								<h4><a href="">Colorblock Scuba</a></h4>
								<p>Web ID: 1089772</p>
							</td>
							<td class="cart_price">
								<p>$59</p>
							</td>
							<td class="cart_quantity">
								<div class="cart_quantity_button">
									<a class="cart_quantity_up" href=""> + </a>
									<input class="cart_quantity_input" type="text" name="quantity" value="1" autocomplete="off" size="2">
									<a class="cart_quantity_down" href=""> - </a>
								</div>
							</td>
							<td class="cart_total">
								<p class="cart_total_price">$59</p>
							</td>
							<td class="cart_delete">
								<a class="cart_quantity_delete" href=""><i class="fa fa-times"></i></a>
							</td>
						</tr>
						<tr>
							<td class="cart_product">
								<a href=""><img src="images/cart/three.png" alt=""></a>
							</td>
							<td class="cart_description">
								<h4><a href="">Colorblock Scuba</a></h4>
								<p>Web ID: 1089772</p>
							</td>
							<td class="cart_price">
								<p>$59</p>
							</td>
							<td class="cart_quantity">
								<div class="cart_quantity_button">
									<a class="cart_quantity_up" href=""> + </a>
									<input class="cart_quantity_input" type="text" name="quantity" value="1" autocomplete="off" size="2">
									<a class="cart_quantity_down" href=""> - </a>
								</div>
							</td>
							<td class="cart_total">
								<p class="cart_total_price">$59</p>
							</td>
							<td class="cart_delete">
								<a class="cart_quantity_delete" href=""><i class="fa fa-times"></i></a>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			
		</div>
	</section> <!--/#cart_items-->

{% endblock %}